### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for EntRelJointDecoder:

### ISSUE THREAD

**Issue by laiww3** [Receiling/UniRE#1]
When I test on scierc dataset, the following errors are reported: error message:
```
Traceback (most recent call last):
  File "entity_relation_joint_decoder.py", line 330, in <module>
    main()
  File "entity_relation_joint_decoder.py", line 316, in main
    model.load_state_dict(state_dict,False)
  File "/home/jsj201-9/anaconda3/envs/unire/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for EntRelJointDecoder:
        size mismatch for embedding_model.bert_encoder.bert_model.embeddings.word_embeddings.weight: copying a param with shapetorch.Size([31090, 768]) from checkpoint, the shape in current model is torch.Size([30522, 768]).
```

**Comment by Receiling** [comment]
It seems the vocabulary size in testing is different from that in training. 
Please check the pre-trained language model for testing on scierc dataset, it should be "allenai/scibert_scivocab_uncased".

**Comment by lww1** [comment]
Thank you very much,I have solved it.

**Comment by lww1** [comment]
> 
> 
> It seems the vocabulary size in testing is different from that in training.
> Please check the pre-trained language model for testing on scierc dataset, it should be "allenai/scibert_scivocab_uncased".

**Comment by laiww3** [comment]
Thank you very much,I have solved it.
