### ISSUE TITLE
如何处理存在overlap的entity？

### ISSUE THREAD

**Issue by yhcc** [Receiling/UniRE#12]
作者你好，感谢你们开源了代码，代码非常整洁易读。我注意到在论文中你们也提到UniRE无法处理overlap entity的情况，在阅读代码时，我发现这部分包含overlap的entity的句子似乎被直接扔掉了，我是根据
https://github.com/Receiling/UniRE/blob/4f59bea2997c8edb5d4659b1cfde9789d5965127/inputs/dataset_readers/ace_reader_for_joint_decoding.py#L174
这个，但我不确定我的理解是否是正确的。希望能得到你的解答，另外从https://github.com/Receiling/UniRE/blob/4f59bea2997c8edb5d4659b1cfde9789d5965127/entity_relation_joint_decoder.py#L281 这里看起来，似乎所有的数据集都被设定为train了，因此所有超过长度的句子也被直接扔掉了。所以我的疑问是 
（1）会把test中含有overlap entity的句子直接扔掉了嘛；  
（2）会扔掉在test中长度超过阈值的sample嘛？

**Comment by Receiling** [comment]
1.是的，UniRE当前的设定是无法处理overlapped entity的，出现entity overlap的情况都会被丢弃（包括train和test），因此论文选用的数据集中overlapped entity占比是极低的，以ACE05为例，训练集中只有一个样本被丢弃，测试集中没有样本被丢弃
2.目前代码中测试集样本超过阈值也会被丢弃，但是同样的，就本论文使用的数据集来说，所设定的阈值是大于数据集样本最大长度的，所以在实际情况中并不会丢弃样本，至于迁移到其他数据集上，可以视具体情况进行调整

**Comment by yhcc** [comment]
好滴，非常感谢你的回复～
