### ISSUE TITLE
关于数据处理

### ISSUE THREAD

**Issue by nlper01** [Receiling/UniRE#13]
ACE05数据拿来后要咋处理？处理成啥格式？可以提供一份处理后的样例看看嘛？
![图片](https://user-images.githubusercontent.com/82627285/182069925-5118b3b6-84a8-4edb-98fc-5401fb10ef3d.png)

**Comment by Receiling** [comment]
1. 首先使用 https://github.com/LorrinWWW/two-are-better-than-one/tree/master/datasets#ace-2005 提供的脚本处理ACE05的原始数据，注意只需要执行前三行命令，执行到`zsh run.zsh`即可，此时可以得到一个ace2005文件夹
2. 然后再使用本repo提供的脚本 https://github.com/Receiling/UniRE/tree/master/data#dataset-processing 处理成最终格式，即执行`./ace2005.sh ace2005`，此时可以得到最终数据ACE2005文件夹

**Comment by Bwin-AI** [comment]
> ACE05数据拿来后要咋处理？处理成啥格式？可以提供一份处理后的样例看看嘛？ ![图片](https://user-images.githubusercontent.com/82627285/182069925-5118b3b6-84a8-4edb-98fc-5401fb10ef3d.png)

请问从哪里获取的ACE05数据，方便告知吗

**Comment by Receiling** [comment]
本repo数据处理部分介绍了所使用的的三个数据集的地址，详见https://github.com/Receiling/UniRE/tree/master/data#dataset-processing

ACE2005的下载地址是https://catalog.ldc.upenn.edu/LDC2006T06

**Comment by Bwin-AI** [comment]
谢谢&nbsp;


?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wang ***@***.***&gt;; 
发送时间: 2022年10月13日(星期四) 下午2:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Receiling/UniRE] 关于数据处理 (Issue #13)





 
本repo数据处理部分介绍了所使用的的三个数据集的地址，详见https://github.com/Receiling/UniRE/tree/master/data#dataset-processing
 
ACE2005的下载地址是https://catalog.ldc.upenn.edu/LDC2006T06

**Comment by Bwin-AI** [comment]
> 2\. 然后再使用本repo提供的脚本 https://github.com/Receiling/UniRE/tree/master/data#dataset-processing 处理成最终格式，即执行`./ace2005.sh ace2005`，此时可以得到最终数据ACE2005文件夹

你好，我用这个方法：
首先使用 https://github.com/LorrinWWW/two-are-better-than-one/tree/master/datasets#ace-2005 提供的脚本处理ACE05的原始数据，注意只需要执行前三行命令，执行到zsh run.zsh即可，此时可以得到一个ace2005文件夹
得到ace2005数据之后，使用./ace2005.sh ace2005指令，报错找不到test.json
![b30f7d83a9532cc4a0a9cd5b0420f1b](https://user-images.githubusercontent.com/58126353/195979037-07f20e8b-6f42-47dd-be60-a52b9229f51c.png)

**Comment by Receiling** [comment]
从报错日志上看，当前目录下没有train.json、dev.json、test.json三个数据文件，
可以先确认下 https://github.com/LorrinWWW/two-are-better-than-one/tree/master/datasets#ace-2005 下的脚本是否成功执行，并且在ace2005文件夹下生成了train.json、dev.json、test.json 三个数据文件。
