### ISSUE TITLE
SciERC数据训练，前几个batch正常输出loss，后面就一直是nan

### ISSUE THREAD

**Issue by yc930401** [Receiling/UniRE#14]
![image](https://user-images.githubusercontent.com/25715774/206964304-ef8228c4-97f9-4882-9ed9-1a6de6bd9689.png)
不知道是什么情况呀？

**Comment by yc930401** [comment]
可能是 allenai/scibert_scivocab_uncased 这个模型的问题，处理数据+运行时都换成bert-base-uncased 就不是nan了

**Comment by ZhichenRen** [comment]
我在ace2005和scirec上碰到了一样的问题，尝试把模型换乘bert-base-uncased仍然没有解决。打印了一下相关变量发现是某些样本经过Bert后的输出变成了nan，从打印的结果来看input_ids和attention_mask都挺正常，有什么解决思路吗？

**Comment by Receiling** [comment]
尝试后没有并复现loss出nan的问题，可以先确认下各个package的版本是否和readme中记录的一致。另外如果要切换model需要重跑数据处理脚步，保证数据处理和模型训练载入的是同一个pretrained-model。

**Comment by ZhichenRen** [comment]
可能是由于transformers版本过高导致的，将其降为4.2.2后不再出现nan。
