### ISSUE TITLE
为什么不使用WebNLG和NYT

### ISSUE THREAD

**Issue by ghost** [Receiling/UniRE#2]
感谢作者分享的代码，我刚接触实体关系联合抽取任务。

为什么作者在文中提到了overlapping triples，可是不用NYT和WebNLG数据集，而要使用ACE呢？

我也注意到，实体关系联合抽取的文章，一部分用ACE，一部分用ＮＹＴ，这之间又有什么区别呢？

感谢楼主！

**Comment by Receiling** [comment]
1. 我们强调的overlapping triples是单个entity参与多个relation的情况，这在 entity relation extraction 数据中是非常常见的，ACE中也包含很多overlapping triples。
2. NYT是一个远程监督数据集，存在大量的噪声，更需要关注的是DS数据的的de-noising。
