### ISSUE TITLE
关于ACE2004交叉验证部分的疑惑

### ISSUE THREAD

**Issue by SihengLi99** [Receiling/UniRE#3]
尊敬的作者，您好！

看了您的文章很受启发，但有些疑惑在于，您是怎么做ACE2004数据集上的5-fold交叉验证的，您是在这五个数据集上跑了五次然后取平均值吗？

其次，如果可以的话，希望获取ACE的数据集。(sihengli99.11.10@gmail.com)

祝您工作顺利，平安喜乐！

**Comment by Receiling** [comment]
1. 就是按照通常5-flod交叉验证的做法，首先将数据集等分成5份，然后逐次选一份作为test set, 其余4份作为train set (然后再从train set中分出一部分作为dev set), 在train set上训练模型并在test set上测试，就可以得到对于每一份test set的测试结果，再对得到的5份测试集的结果取平均值就是最终的结果。
2. 考虑到ACE数据集的版权问题，建议到论文中提供的官方地址下载，对应的数据处理的脚本也在repo提供了。

**Comment by SihengLi99** [comment]
十分感谢！
