### ISSUE TITLE
关于评估的一个小问题

### ISSUE THREAD

**Issue by lyhuohuo** [Receiling/UniRE#8]
你好，我想请教一下关于数据集中两个实体之间关系为None的是如何在评估里面处理的？

**Comment by Receiling** [comment]
由于联合实体关系抽取需要同时识别实体和关系，所以一般不会考虑None关系，在给定实体的关系分类任务下考虑None关系的情况才比较常见。
本文所使用的ACE2004、ACE2005、SciERC三个数据集均不包含None关系。

**Comment by lyhuohuo** [comment]
了解啦，感谢解答！！

**Comment by lyhuohuo** [comment]
不好意思，还有一个问题，对于entity的评估，是对有关系的entity进行评估还是文本中所有的entity？

**Comment by Receiling** [comment]
是对所有的entity进行评估。

**Comment by lyhuohuo** [comment]
谢谢！
